#!/usr/bin/env python

import sys
import asyncio
import asyncpg
import datetime

from config.loaders import load_postgresql_config


async def main():
    cfg, err = load_postgresql_config()
    if err is not None:
        print(err)
        sys.exit(1)

    conn = await asyncpg.connect(cfg.uri)
    # # Execute a statement to create a new table.
    print("creating health check table")
    try:
        await conn.execute(health_check_table())
    except asyncpg.exceptions.DuplicateTableError:
        print("health check table table already exists")

    await conn.close()


def health_check_table():
    return """
CREATE TABLE spyglass_health_status_test2 (
    timestamp        timestamp without time zone,
    website          text,
    path             text,
    healthy          boolean,
    status_code      smallint,
    response_time_ms integer
) PARTITION BY RANGE (timestamp);
    """

if __name__ == "__main__":
    asyncio.run(main())
